// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB1p4NBeUKd0nSm6eIP-MONlr34h8aVmBA',
    appId: '1:482308073899:web:2e071528a16ed910694aee',
    messagingSenderId: '482308073899',
    projectId: 'fruitecommerce-20c5c',
    authDomain: 'fruitecommerce-20c5c.firebaseapp.com',
    storageBucket: 'fruitecommerce-20c5c.firebasestorage.app',
    measurementId: 'G-26ZB250K46',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCqMNEY7Hq-VISsYHrX7NDyFxRTW8Voqng',
    appId: '1:482308073899:android:e9c5930e20515a4a694aee',
    messagingSenderId: '482308073899',
    projectId: 'fruitecommerce-20c5c',
    storageBucket: 'fruitecommerce-20c5c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAK_NJgf_8kkYyLQx-pTuWnbKHKYhaZMRc',
    appId: '1:482308073899:ios:7ee023bb501159ac694aee',
    messagingSenderId: '482308073899',
    projectId: 'fruitecommerce-20c5c',
    storageBucket: 'fruitecommerce-20c5c.firebasestorage.app',
    androidClientId: '482308073899-j4agknb37o7v7sp3g3klhlonm0a4l9qi.apps.googleusercontent.com',
    iosClientId: '482308073899-38uhnp574b8kgneggv6oegh6rrogh1t8.apps.googleusercontent.com',
    iosBundleId: 'com.example.dashboard',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAK_NJgf_8kkYyLQx-pTuWnbKHKYhaZMRc',
    appId: '1:482308073899:ios:7ee023bb501159ac694aee',
    messagingSenderId: '482308073899',
    projectId: 'fruitecommerce-20c5c',
    storageBucket: 'fruitecommerce-20c5c.firebasestorage.app',
    androidClientId: '482308073899-j4agknb37o7v7sp3g3klhlonm0a4l9qi.apps.googleusercontent.com',
    iosClientId: '482308073899-38uhnp574b8kgneggv6oegh6rrogh1t8.apps.googleusercontent.com',
    iosBundleId: 'com.example.dashboard',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB1p4NBeUKd0nSm6eIP-MONlr34h8aVmBA',
    appId: '1:482308073899:web:8ddc5d2cd92fa1f4694aee',
    messagingSenderId: '482308073899',
    projectId: 'fruitecommerce-20c5c',
    authDomain: 'fruitecommerce-20c5c.firebaseapp.com',
    storageBucket: 'fruitecommerce-20c5c.firebasestorage.app',
    measurementId: 'G-C45MW36MLH',
  );
}
